<?php

namespace Database\Seeders;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
     public function run(): void
    {
        $products = [
            [
                'name' => 'Howling Blaster',
                'model' => 'HB-99',
                'category_id' => 1,
                'country_id' => 1,
                'price' => 1999.99,
                'stock' => 20,
                'image_public_id' => '7_hiuwgj',
                'description' => 'Advanced infantry weapon with a surprisingly loud bark.',
            ],
            [
                'name' => 'Panzer Pup',
                'model' => 'T-REX-3',
                'category_id' => 2,
                'country_id' => 2,
                'price' => 750000.00,
                'stock' => 5,
                'image_public_id' => 'Goat_Riding_a_Plane_algao4',
                'description' => 'Heavy-duty tank with adorable intimidation factor.',
            ],
            [
                'name' => 'Boom Duck',
                'model' => 'QUA-155',
                'category_id' => 3,
                'country_id' => 3,
                'price' => 120000.00,
                'stock' => 8,
                'image_public_id' => '10_lsvaup',
                'description' => 'Quack-powered artillery for serious splash damage.',
            ],
            [
                'name' => 'Sealion Sub',
                'model' => 'SS-SEA9',
                'category_id' => 4,
                'country_id' => 4,
                'price' => 2200000.00,
                'stock' => 2,
                'image_public_id' => '6_h478qr',
                'description' => 'Stealthy and slippery naval force for covert missions.',
            ],
            [
                'name' => 'Hawk Jet',
                'model' => 'HJ-EAGLE1',
                'category_id' => 5,
                'country_id' => 5,
                'price' => 1800000.00,
                'stock' => 4,
                'image_public_id' => '1_gtnjtd',
                'description' => 'Sky dominance with feathers and fire.',
            ],
            [
                'name' => 'Flamethrower Ferret',
                'model' => 'FF-14',
                'category_id' => 1,
                'country_id' => 1,
                'price' => 3499.99,
                'stock' => 15,
                'image_public_id' => '5_urftpp',
                'description' => 'Small but spicy assault weapon for tight situations.',
            ],
            [
                'name' => 'Meow Mortar',
                'model' => 'CAT-88',
                'category_id' => 3,
                'country_id' => 2,
                'price' => 89999.99,
                'stock' => 10,
                'image_public_id' => '3_xhjabw',
                'description' => 'Tactical artillery with precision and purring.',
            ],
            [
                'name' => 'Crocodile Cruiser',
                'model' => 'NAV-CROC-1',
                'category_id' => 4,
                'country_id' => 3,
                'price' => 999999.99,
                'stock' => 3,
                'image_public_id' => '4_jxpz2o',
                'description' => 'Naval beast built for amphibious assault.',
            ],
            [
                'name' => 'Bat Bomber',
                'model' => 'BAT-WINGZ',
                'category_id' => 5,
                'country_id' => 4,
                'price' => 2750000.00,
                'stock' => 2,
                'image_public_id' => 'photo_2025-07-12_00-30-29_a4vpu7',
                'description' => 'Silent nighttime bombardment straight from the caves.',
            ],
            [
                'name' => 'Penguin Patrol',
                'model' => 'ICE-INF-7',
                'category_id' => 1,
                'country_id' => 5,
                'price' => 1300.00,
                'stock' => 50,
                'image_public_id' => 'photo_2025-07-12_00-30-39_wtv0eb',
                'description' => 'Cold-weather infantry ready to waddle into war.',
            ],
            [
                'name' => 'Glock 19',
                'model' => 'ICE-INF-7',
                'category_id' => 1,
                'country_id' => 1,
                'price' => 1400.00,
                'stock' => 19,
                'image_public_id' => '48a046f4-17e3-46bf-8d14-14609207f76e_xa3ikl',
                'description' => 'Smartly balanced weapon for both beginners and experts.',
            ],
             [
                'name' => 'Beretta M9',
                'model' => 'ICE-INF-7',
                'category_id' => 1,
                'country_id' => 2,
                'price' => 1500.00,
                'stock' => 17,
                'image_public_id' => 'Beretta_Finally_Inoxes_the_PX4_Storm____Guns_com_drte2s',
                'description' => 'Designed for accuracy under pressure and fast recovery.',
            ],
             [
                'name' => 'Desert Eagle',
                'model' => 'ICE-INF-7',
                'category_id' => 1,
                'country_id' => 3,
                'price' => 1600.00,
                'stock' => 13,
                'image_public_id' => 'Sci-Fi_Sniper_Rifle_Ashley_Culbertson_zvfdg5',
                'description' => 'Elite tactical handgun for professionals in the field.',
            ], [
                'name' => 'Canik TP9 Elite',
                'model' => 'ICE-INF-7',
                'category_id' => 1,
                'country_id' => 4,
                'price' => 1700.00,
                'stock' => 11,
                'image_public_id' => 'Zach_on_Instagram___Mid_Range_Monster__I_am_yvahgf',
                'description' => 'Heavy-duty pistol with armor-piercing capability.',
            ], [
                'name' => 'HK VP9',
                'model' => 'ICE-INF-7',
                'category_id' => 1,
                'country_id' => 5,
                'price' => 1800.00,
                'stock' => 10,
                'image_public_id' => 'ca57b6d3-da72-466b-8ada-f7ed0d93b88f_qmei4d',
                'description' => 'Compact size without sacrificing firepower.',
            ], [
                'name' => 'Kimber Custom II',
                'model' => 'ICE-INF-7',
                'category_id' => 1,
                'country_id' => 6,
                'price' => 1900.00,
                'stock' => 21,
                'image_public_id' => 'cbe19c96-e7af-48f4-ac8a-23704641f3cd_arxjty',
                'description' => 'Ergonomic grip for maximum control during rapid fire.',
            ], [
                'name' => 'Steyr M9-A1',
                'model' => 'ICE-INF-7',
                'category_id' => 1,
                'country_id' => 7,
                'price' => 2000.00,
                'stock' => 15,
                'image_public_id' => '35_Strangely_Odd_Modded_Weapons__-_Wtf_Gallery_c54our',
                'description' => 'Designed for speed, stealth, and deadly efficiency.',
            ], [
                'name' => 'Remington 1911 R1',
                'model' => 'ICE-INF-7',
                'category_id' => 1,
                'country_id' => 8,
                'price' => 2100.00,
                'stock' => 32,
                'image_public_id' => 'Kick-Ass_Zombie_Weapons_In_Case_of_._bqp4kf',
                'description' => 'Concealable pistol with reliable safety and fast action.',
            ],
                // [
            //     'name' => 'FNX-45 Tactical',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 9,
            //     'price' => 2200.00,
            //     'stock' => 30,
            //     'image_public_id' => '97946d85-6e73-4e43-8bfc-85b5a43d7b04_vvy8ar',
            //     'description' => 'Trusted sidearm by law enforcement and military worldwide.',
            // ], [
            //     'name' => 'Springfield XD',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 10,
            //     'price' => 2300.00,
            //     'stock' => 28,
            //     'image_public_id' => 'ccd29176-e97d-4b92-a564-51b7a2b3450b_vcvids',
            //     'description' => 'Sleek modern design with laser sight compatibility.',
            // ], [
            //     'name' => 'Taurus PT92',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 11,
            //     'price' => 2400.00,
            //     'stock' => 26,
            //     'image_public_id' => 'suburban_men_here_are_the_50_best_photos_this_week_rz4mm6',
            //     'description' => 'Precision-engineered weapon with minimal recoil and smooth trigger.',
            // ], [
            //     'name' => 'Ruger SR9',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 12,
            //     'price' => 2500.00,
            //     'stock' => 24,
            //     'image_public_id' => '_SUNRISE__-__Восход__An_excellent_weapon_with_an_trrdae',
            //     'description' => 'High-caliber pistol with stopping power for critical missions.',
            //     ],
            //  [
            //     'name' => 'Browning Hi-Power',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 13,
            //     'price' => 2700.00,
            //     'stock' => 22,
            //     'image_public_id' => '1e3b5b8c-1fed-4db1-9876-92ec46fb99ab_dws2ua',
            //     'description' => 'Desert combat handgun built for harsh environments.',
            // ], [
            //     'name' => 'CZ 75',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 14,
            //     'price' => 2600.00,
            //     'stock' => 20,
            //     'image_public_id' => 'Exploring_the_Effective_Range_of_a__450_Bushmaster_btj2do',
            //     'description' => 'Small but deadly – perfect for quick-draw situations.',
            // ], [
            //     'name' => 'Walther P99',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 15,
            //     'price' => 2800.00,
            //     'stock' => 20,
            //     'image_public_id' => '3712d87e-8287-41d6-b7cd-49a3f97a100f_cp6uff',
            //     'description' => 'Durable steel-frame pistol used by elite special forces.',
            // ], [
            //     'name' => 'FN Five-seveN',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 16,
            //     'price' => 2900.00,
            //     'stock' => 18,
            //     'image_public_id' => 'There_s_no_perfect_home_defense_rifle_since_wqejak',
            //     'description' => 'Classic revolver with timeless design and deadly accuracy.',
            // ], [
            //     'name' => 'Smith & Wesson M&P',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 17,
            //     'price' => 3000.00,
            //     'stock' => 16,
            //     'image_public_id' => 'a1aa6dc4-1db0-4219-8f33-87f5a1982fef_jj5qv1',
            //     'description' => 'Tactical pistol with extended magazine and suppressor support.',
            // ], [
            //     'name' => 'Heckler & Koch USP',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 18,
            //     'price' => 4000.00,
            //     'stock' => 14,
            //     'image_public_id' => 'c2add8f4-8bad-4544-81a6-f674d2084d3b_rg1blo',
            //     'description' => 'Lightweight sidearm ideal for covert military operations.',
            // ], [
            //     'name' => 'SIG Sauer P226',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 19,
            //     'price' => 4100.00,
            //     'stock' => 12,
            //     'image_public_id' => 'Tumblr__Image_eqtgpq',
            //     'description' => 'Reliable semi-automatic pistol with high precision and fast reload.',
            // ], [
            //     'name' => 'Beretta Me',
            //     'model' => 'ICE-INF-7',
            //     'category_id' => 1,
            //     'country_id' => 20,
            //     'price' => 4100.00,
            //     'stock' => 10,
            //     'image_public_id' => 'DDM4_PDW_bvhakb',
            //     'description' => 'Compact and powerful handgun designed for close-range defense.',
            // ],
                ['name' => 'Beretta M9', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 1, 'price' => 4100.00, 'stock' => 10, 'image_public_id' => 'download_11_r5n5ud', 'description' => 'Compact and powerful handgun designed for close-range defense.'],
                ['name' => 'Glock 19', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 2, 'price' => 3950.00, 'stock' => 8, 'image_public_id' => 'What_do_you_think__kkxbmc', 'description' => 'Reliable and widely used pistol suitable for all environments.'],
                ['name' => 'Desert Eagle', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 3, 'price' => 7200.00, 'stock' => 5, 'image_public_id' => 'download_10_gbfa4x', 'description' => 'Heavy-duty handgun with immense stopping power.'],
                ['name' => 'Colt M1911', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 4, 'price' => 4300.00, 'stock' => 12, 'image_public_id' => 'f9e21178-df0c-49e8-b8f5-ab16e0c361e1_anonw2', 'description' => 'Classic American pistol known for durability and precision.'],
                ['name' => 'SIG Sauer P226', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 5, 'price' => 4600.00, 'stock' => 9, 'image_public_id' => 'ea47126e-f8dc-4e78-b5e2-353333100fe4_tdrtsy', 'description' => 'Preferred by military units for its reliability and control.'],
                ['name' => 'Heckler & Koch USP', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 6, 'price' => 4700.00, 'stock' => 6, 'image_public_id' => '587462d1-b888-4796-bb9f-45dc022beda7_re2jo7', 'description' => 'German-engineered pistol offering high accuracy and quality.'],
                ['name' => 'Smith & Wesson M&P', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 7, 'price' => 3900.00, 'stock' => 11, 'image_public_id' => 'This_specialized_military_unit_is_part_of_the_vrmd4n', 'description' => 'Modern polymer-framed pistol built for law enforcement.'],
                ['name' => 'FN Five-seveN', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 8, 'price' => 5300.00, 'stock' => 7, 'image_public_id' => 'download_3_w5fnsz', 'description' => 'Lightweight pistol with armor-piercing capability.'],
                ['name' => 'Walther P99', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 9, 'price' => 4200.00, 'stock' => 10, 'image_public_id' => 'download_4_x4bqzo', 'description' => 'Well-balanced pistol used by special forces worldwide.'],
                // ['name' => 'CZ 75', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 10, 'price' => 4100.00, 'stock' => 6, 'image_public_id' => 'download_5_ah23um', 'description' => 'Czech-made pistol with excellent grip and recoil control.'],
                // ['name' => 'Browning Hi-Power', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 11, 'price' => 4400.00, 'stock' => 4, 'image_public_id' => 'download_6_cyw9s6', 'description' => 'Iconic 9mm pistol known for its high capacity.'],
                // ['name' => 'Ruger SR9', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 12, 'price' => 3750.00, 'stock' => 13, 'image_public_id' => 'download_2_bcepxw', 'description' => 'Slim and lightweight pistol with modern safety features.'],
                // ['name' => 'Taurus PT92', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 13, 'price' => 3600.00, 'stock' => 10, 'image_public_id' => '5_urftpp', 'description' => 'Affordable and reliable Brazilian-manufactured handgun.'],
                // // ['name' => 'Springfield XD', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 14, 'price' => 4000.00, 'stock' => 9, 'image_public_id' => '9_ex91dg', 'description' => 'Ergonomic design built for performance and accuracy.'],
                // ['name' => 'Remington 1911 R1', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 16, 'price' => 4600.00, 'stock' => 5, 'image_public_id' => 'download_9_hdqvu4', 'description' => 'A modern take on the classic military sidearm.'],
                // ['name' => 'Steyr M9-A1', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 17, 'price' => 4300.00, 'stock' => 6, 'image_public_id' => 'Military_drone_with_a_bomb_at_sunset__Combat_drone_vqxnjx', 'description' => 'Futuristic design with built-in safety and accuracy.'],
                // ['name' => 'Kimber Custom II', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 18, 'price' => 4900.00, 'stock' => 5, 'image_public_id' => 'China_Set_to_Launch_New_Crewed_Mission_into_Space_dcwuuk', 'description' => 'Precision-crafted handgun for professional shooters.'],
                // ['name' => 'Canik TP9 Elite', 'model' => 'PlN-7', 'category_id' => 5, 'country_id' => 20, 'price' => 3850.00, 'stock' => 7, 'image_public_id' => 'Fighter_fmp78d', 'description' => 'Turkish-made pistol known for value and performance.'],

        ];



        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
