<!DOCTYPE html>
<html>
<body style="margin:0; padding:0; font-family: 'Poppins', Arial, sans-serif; background-color: #0A0A1A; color: #E0E0FF;">
    <table width="100%" cellspacing="0" cellpadding="0" bgcolor="#0A0A1A">
        <tr>
            <td align="center" style="padding: 20px 0;">
                <table width="600" cellspacing="0" cellpadding="0" bgcolor="#0A0A1A" style="border: 1px solid #00F5FF; border-radius: 0; box-shadow: 0 0 20px rgba(151, 71, 255, 0.3);">
                    
                    <tr>
                        <td bgcolor="#0A0A1A" style="padding: 30px; text-align: center; border-bottom: 1px solid #9747FF;">
                            <h1 style="margin:0; font-size: 28px; color: #00F5FF; text-shadow: 0 0 10px rgba(0, 245, 255, 0.5); letter-spacing: 1px;">
                                🛒 Complete Your Order
                            </h1>
                            <p style="color: #E0E0FF; margin: 10px 0 0 0; font-size: 14px;">
                                Secure checkout powered by Ternary Arsenal
                            </p>
                        </td>
                    </tr>
                    
                    <tr>
                        <td style="padding: 30px;">
                            <p style="margin: 0 0 15px 0;">Hello, valued customer 👋</p>
                            <p style="margin: 0 0 20px 0;">
                                You have a pending item waiting to be purchased. Click the button below to complete your secure checkout.
                            </p>

                            <table cellspacing="0" cellpadding="0" style="margin: 30px 0;">
                                <tr>
                                    <td align="center">
                                        <a href="{{ $checkoutUrl }}" style="background-color: #9747FF; color: white; text-decoration: none; padding: 16px 32px; border-radius: 0; font-weight: bold; display: inline-block; border: 1px solid #00F5FF; text-transform: uppercase; letter-spacing: 1px; box-shadow: 0 0 15px rgba(151, 71, 255, 0.5); transition: all 0.3s;">
                                            Checkout Now
                                        </a>
                                    </td>
                                </tr>
                            </table>

                            <table width="100%" cellspacing="0" cellpadding="0" style="margin: 20px 0;">
                                <tr>
                                    <td align="center" style="padding: 10px 0;">
                                        <div style="height: 1px; background: linear-gradient(90deg, transparent, #00F5FF, transparent);"></div>
                                    </td>
                                </tr>
                            </table>

                            <table width="100%" cellspacing="0" cellpadding="0" style="margin: 25px 0; border: 1px dashed #00F5FF; background-color: rgba(10, 10, 26, 0.7);">
                                <tr>
                                    <td align="center" style="padding: 20px;">
                                        <p style="margin: 0 0 15px 0; color: #00F5FF; font-size: 12px; letter-spacing: 1px;">SCAN TO PAY</p>
                                        <img src="{{ $message->embed($qrPath) }}" alt="QR Code" style="max-width: 180px; height: auto; border: 1px solid #9747FF; padding: 5px; background: white;">
                                        <p style="margin: 15px 0 0 0; color: #FF00E5; font-size: 11px; font-family: monospace;">Secure • Expires in 24h</p>
                                    </td>
                                </tr>
                            </table>

                            <p style="margin: 20px 0 0 0; font-size: 12px; line-height: 1.6;">
                                This payment link is encrypted and generated by <span style="color: #00F5FF;">Ternary Arsenal</span>, developed by the creative team: 
                                <strong style="color: #FF00E5;">Zeyad, Tahany, Shams, and Two Zeros & One</strong>.
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding: 20px; text-align: center; border-top: 1px solid #9747FF;">
                            <p style="margin: 0; color: #00F5FF; font-size: 10px; letter-spacing: 1px;">© 2025 Ternary Arsenal</p>
                            <p style="margin: 5px 0 0 0; color: #E0E0FF; font-size: 9px; font-family: monospace;">Built by Team Cyber • #BinaryRebels</p>
                        </td>
                    </tr>

                </table>
            </td>
        </tr>
    </table>
</body>
</html>
